# Generated by Django 3.0.3 on 2020-06-26 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.AutoField(primary_key=True, serialize=False)),
                ('attended', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchid', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=35)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid_ai', models.AutoField(primary_key=True, serialize=False)),
                ('classid', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('batch', models.TextField()),
                ('section', models.CharField(blank=True, max_length=1, null=True)),
                ('labgroup', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('classcourseid', models.AutoField(primary_key=True, serialize=False)),
                ('ac_year', models.TextField(blank=True, null=True)),
                ('sem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollid', models.AutoField(primary_key=True, serialize=False)),
                ('ac_year', models.TextField(blank=True, null=True)),
                ('sem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examid', models.AutoField(primary_key=True, serialize=False)),
                ('examtype', models.CharField(max_length=6)),
                ('edate', models.DateField(blank=True, null=True)),
                ('total', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'exam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureid', models.AutoField(primary_key=True, serialize=False)),
                ('timedate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained', models.IntegerField()),
            ],
            options={
                'db_table': 'marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'student_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(blank=True, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'timetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('role', models.BooleanField(blank=True, default=True, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('uid', models.OneToOneField(blank=True, db_column='UID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='BranchCourse',
            fields=[
                ('branchid', models.OneToOneField(db_column='branchid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.Branch')),
            ],
            options={
                'db_table': 'branch_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClasscourse',
            fields=[
                ('studentid', models.OneToOneField(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.Student')),
            ],
            options={
                'db_table': 'student_classcourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.OneToOneField(db_column='facultyid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('facultyname', models.CharField(max_length=60)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
    ]
