# Generated by Django 3.0.3 on 2020-05-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acitve',
            new_name='active',
        ),
    ]
