# Generated by Django 3.0.3 on 2020-05-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200517_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_faculty',
            new_name='is_Faculty',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_Student',
        ),
    ]
