# Generated by Django 3.0.3 on 2020-05-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200517_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='isStudent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='role',
        ),
    ]
