# Generated by Django 3.0.3 on 2020-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200517_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isStudent',
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
